server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB_JAVA_SPRING_TESTS?createDatabaseIfNotExist=true
    username: root
    password: root